language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack:
    secure: Jhp2alkZkXwAqJyHndLSoRoa3lWoZ3SciPhNUvNNw5zjX/1vAc6WKPP0VNAjcDz8sxwKoUgta6Kw8yfdwEel9STOHJ4JIGC20x+wSulwkQPXwXM2gUOD87pefO+Dfqx3Gl+DA1SPzvNzpbD6CL4phn/u9dM3ITAk6nsMGG7CaGVhZiamGNLUp4E3wt8zux/tFkoMd5I+OKZ7sZR5vPA+GZwDhN3FrKmxwV/WMqCnmRknsOXBVeQi40DygW9uwYacoWUFXbriAyqPnGB+TDNIEQnds3LnPdZpw5vtsyYYVseBsLMWIILkQeIDIYMgbJAWlZT7naIgDGiltKMeHQzfx/kfPKZE0KaJAy6aM6XrJHsGyABg6kTyGIqszkhC/OsNzvJtSKmUXInklzyrPf14TmP7PSuqqZH8BxEFU9lDeWTxkXjxkPoNyQRLmjMvoiQC7bkVfts62uXzwPAieeP/7+dzPVcSzYki+959Vw0JCPhEq5JD260HR/aWnl8HZTWfEYb5t8bLXhkaw+EmeMrrgfLZrL2yS6YlHVeN57H3BSfahu7kA3VVq0WQoHKuJka/Uk6Tm8O/XAmaI6iQTOk9dCIBTKqPrdwrXDHqhULQFZ0bq7IWk2/+5nvfXZ1FW9QVagNcDGlKNHr15dajplDpMI6kRugf0xQyqaZWexMx7xQ=
